const ORDERS_FETCH_SUCCEED = 'ORDERS_FETCH_SUCCEED';
const UPDATE_REQUEST = "UPDATE_REQUEST";
const START_FETCHING = "START_FETCHING";
const END_FETCHING = "END_FETCHING";
const ORDER_EXCLUDED = "ORDER_EXCLUDED";

export default {
  ORDERS_FETCH_SUCCEED,
  UPDATE_REQUEST,
  START_FETCHING,
  END_FETCHING,
  ORDER_EXCLUDED,
}
