const DATA_FETCH_SUCCEED = 'DATA_FETCH_SUCCEED';
const START_FETCHING = "START_FETCHING";
const END_FETCHING = "END_FETCHING";
const TEST_DATA_UPDATED ="TEST_DATA_UPDATED";
const TEST_ADDED ="TEST_ADDED";

export default {
  DATA_FETCH_SUCCEED,
  START_FETCHING,
  END_FETCHING,
  TEST_DATA_UPDATED,
  TEST_ADDED,
}
