export default {
  TESTS_TABLE_DATA_LOADING_STARTED: 'TESTS_TABLE_DATA_LOADING_STARTED',
  TESTS_TABLE_DATA_LOADING_ENDED: 'TESTS_TABLE_DATA_LOADING_ENDED',
  TESTS_TABLE_TESTS_FETCH_SUCCEED: 'TESTS_TABLE_TESTS_FETCH_SUCCEED',
  TESTS_TABLE_FILTER_BY_NAME_TRIGGERED: 'TESTS_TABLE_FILTER_BY_NAME_TRIGGERED',
};
