const TESTS_TABLE_FETCH_SUCCEED = 'TESTS_TABLE_FETCH_SUCCEED';
const TESTS_TABLE_DATA_LOADING_STARTED = 'TESTS_TABLE_DATA_LOADING_STARTED';
const TESTS_TABLE_SUBMIT_FILTERS = 'TESTS_TABLE_SUBMIT_FILTERS';
const TESTS_TABLE_CLEAR_FILTERS = 'TESTS_TABLE_CLEAR_FILTERS';

export default {
  TESTS_TABLE_FETCH_SUCCEED,
  TESTS_TABLE_DATA_LOADING_STARTED,
  TESTS_TABLE_SUBMIT_FILTERS,
  TESTS_TABLE_CLEAR_FILTERS,
};
