const FIELD_ADDED = "FIELD_ADDED";
const FIELD_UPDATED = "FIELD_UPDATED";
const FIELD_DELETED = "FIELD_DELETED";
const DATA_VALIDATED = 'DATA_VALIDATED';
const GOT_DATA = 'GOT_DATA';


export default {
  FIELD_ADDED,
  FIELD_UPDATED,
  FIELD_DELETED,
  DATA_VALIDATED,
  GOT_DATA,
}
