const CHAINS_FETCH_SUCCEED = 'CHAINS_FETCH_SUCCEED';
const START_FETCHING = "START_FETCHING";
const END_FETCHING = "END_FETCHING"

export default {
  CHAINS_FETCH_SUCCEED,
  START_FETCHING,
  END_FETCHING,
}
