const CHAINS_FETCH_SUCCEED = 'CHAINS_FETCH_SUCCEED';
const TESTS_FETCH_SUCCEED = 'TESTS_FETCH_SUCCEED';
const START_FETCHING = "START_FETCHING";
const END_FETCHING = "END_FETCHING";
const CHAINS_FILTER_BY_NAME = 'CHAINS_FILTER_BY_NAME';

export default {
  CHAINS_FETCH_SUCCEED,
  TESTS_FETCH_SUCCEED,
  START_FETCHING,
  END_FETCHING,
  CHAINS_FILTER_BY_NAME,
}
