const FILTER_TEST_FETCH_SUCCEED = 'FILTER_TEST_FETCH_SUCCEED';
const FILTER_START_FETCHING = "FILTER_START_FETCHING";
const FILTER_END_FETCHING = "FILTER_END_FETCHING";

export default {
  FILTER_TEST_FETCH_SUCCEED,
  FILTER_START_FETCHING,
  FILTER_END_FETCHING,
}
