const FILTER_TEST_FETCH_SUCCEED = 'FILTER_TEST_FETCH_SUCCEED';
const FILTER_START_FETCHING = "FILTER_START_FETCHING";
const FILTER_END_FETCHING = "FILTER_END_FETCHING";
const CHAIN_MASTER_TEST_SELECTED = 'CHAIN_MASTER_TEST_SELECTED';
const CHAIN_MASTER_TEST_REORDERED = 'CHAIN_MASTER_TEST_REORDERED';
const CHAIN_MASTER_TEST_REMOVED = 'CHAIN_MASTER_TEST_REMOVED';

export default {
  FILTER_TEST_FETCH_SUCCEED,
  FILTER_START_FETCHING,
  FILTER_END_FETCHING,
  CHAIN_MASTER_TEST_SELECTED,
  CHAIN_MASTER_TEST_REORDERED,
  CHAIN_MASTER_TEST_REMOVED,
}
